version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrental
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - carrental-network

  backend:
    build: ./carrental-backend
    container_name: carrental-backend
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carrental?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - carrental-network

  frontend:
    build: ./carrental-frontend
    container_name: carrental-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - carrental-network

networks:
  carrental-network:
    driver: bridge

volumes:
  mysql-data: